openapi: 3.0.1
info:
  contact:
    email: support@chainloop.dev
    name: Chainloop Support
    url: https://chainloop.dev
  termsOfService: https://chainloop.dev/terms
  title: Chainloop Controlplane API
  version: "1.0"
externalDocs:
  description: Chainloop Official Documentation
  url: https://docs.chainloop.dev
servers:
- url: https://cp.chainloop.dev/
security:
- bearerToken: []
tags:
- description: Referrer service for discovering referred content by digest
  name: ReferrerService
paths:
  /discover/shared/{digest}:
    get:
      description: Returns the referrer item for a given digest in the public shared
        index
      operationId: ReferrerService_DiscoverPublicShared
      parameters:
      - description: Digest is the unique identifier of the referrer to discover
        in: path
        name: digest
        required: true
        schema:
          type: string
      - description: |-
          Kind is the optional type of referrer, i.e CONTAINER_IMAGE, GIT_HEAD, ...
          Used to filter and resolve ambiguities
        in: query
        name: kind
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1DiscoverPublicSharedResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Discover public shared referrer
      tags:
      - ReferrerService
  /discover/{digest}:
    get:
      description: Returns the referrer item for a given digest in the organizations
        of the logged-in user
      operationId: ReferrerService_DiscoverPrivate
      parameters:
      - description: Digest is the unique identifier of the referrer to discover
        in: path
        name: digest
        required: true
        schema:
          type: string
      - description: |-
          Kind is the optional type of referrer, i.e CONTAINER_IMAGE, GIT_HEAD, ...
          Used to filter and resolve ambiguities
        in: query
        name: kind
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1ReferrerServiceDiscoverPrivateResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Discover private referrer
      tags:
      - ReferrerService
components:
  schemas:
    protobufAny:
      additionalProperties:
        type: object
      example:
        '@type': '@type'
      properties:
        '@type':
          type: string
      type: object
    rpcStatus:
      example:
        code: 0
        details:
        - '@type': '@type'
        - '@type': '@type'
        message: message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
      type: object
    v1DiscoverPublicSharedResponse:
      description: Response for the DiscoverPublicShared method
      example:
        result:
          downloadable: true
          metadata:
            key: metadata
          public: true
          references:
          - null
          - null
          kind: kind
          digest: digest
          created_at: 2000-01-23T04:56:07.000+00:00
          annotations:
            key: annotations
      properties:
        result:
          $ref: '#/components/schemas/v1ReferrerItem'
      title: DiscoverPublicSharedResponse
      type: object
    v1ReferrerItem:
      description: It represents a referrer object in the system
      example:
        downloadable: true
        metadata:
          key: metadata
        public: true
        references:
        - null
        - null
        kind: kind
        digest: digest
        created_at: 2000-01-23T04:56:07.000+00:00
        annotations:
          key: annotations
      properties:
        digest:
          title: "Digest of the referrer, i.e sha256:deadbeef or sha1:beefdead"
          type: string
        kind:
          description: "Kind of referrer, i.e CONTAINER_IMAGE, GIT_HEAD, ..."
          type: string
        downloadable:
          title: Downloadable indicates whether the referrer is downloadable or not
            from CAS
          type: boolean
        public:
          title: Public indicates whether the referrer is public since it belongs
            to a public workflow
          type: boolean
        references:
          items:
            $ref: '#/components/schemas/v1ReferrerItem'
          title: References contains the list of related referrer items
          type: array
        created_at:
          format: date-time
          title: CreatedAt is the timestamp when the referrer was created
          type: string
        metadata:
          additionalProperties:
            type: string
          title: Metadata contains additional descriptive information about the referrer
          type: object
        annotations:
          additionalProperties:
            type: string
          title: Annotations are key-value pairs associated with the referrer
          type: object
      title: ReferrerItem
      type: object
    v1ReferrerServiceDiscoverPrivateResponse:
      description: Response for the DiscoverPrivate method
      example:
        result:
          downloadable: true
          metadata:
            key: metadata
          public: true
          references:
          - null
          - null
          kind: kind
          digest: digest
          created_at: 2000-01-23T04:56:07.000+00:00
          annotations:
            key: annotations
      properties:
        result:
          $ref: '#/components/schemas/v1ReferrerItem'
      title: ReferrerServiceDiscoverPrivateResponse
      type: object
  securitySchemes:
    bearerToken:
      description: Bearer token for authentication
      in: header
      name: Authorization
      type: apiKey
x-original-swagger-version: "2.0"
